name: Smoke test via pnpm
on: push

permissions:
  contents: read

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: install
        run: pnpm install && git status --porcelain
      - run: pnpm build
      - name: run chromatic
        run: pnpm dlx chromatic --build-script-name build-test-storybook --exit-zero-on-changes --force-rebuild
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.SMOKE_TESTS_CHROMATIC_PROJECT_TOKEN }}
