name: Smoke test via Node 18
on: push

permissions:
  contents: read

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Add engines to package.json to enforce above version of node
        run: echo "`jq '.engines.node="18.x"' package.json`" > package.json

      - run: corepack enable
      - run: yarn
      - run: yarn build
      - uses: ./
        with:
          buildScriptName: build-test-storybook
          exitZeroOnChanges: true
          forceRebuild: true
          onlyChanged: true
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.SMOKE_TESTS_CHROMATIC_PROJECT_TOKEN }}

      - name: Revert engines addition to package.json
        run: echo "`jq 'del(.engines)' package.json`" > package.json
